export const elements = {
  div: "div",
  span: "span",
  p: "p",
  h1: "h1",
  h2: "h2",
  h3: "h3",
  h4: "h4",
  h5: "h5",
  h6: "h6",
  ul: "ul",
  ol: "ol",
  li: "li",
  a: "a",
  button: "button",
  input: "input",
  label: "label",
  form: "form",
  textarea: "textarea",
  select: "select",
  option: "option",
  img: "img",
  nav: "nav",
  header: "header",
  footer: "footer",
  section: "section",
  article: "article",
  aside: "aside",
  main: "main",
  figure: "figure",
  figcaption: "figcaption",
  table: "table",
  thead: "thead",
  tbody: "tbody",
  tr: "tr",
  th: "th",
  td: "td",
} as const;

export type ElementKey = keyof typeof elements;
